### ISSUE TITLE
Not processed elements in NodeType and NodeTemplate

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#101]
The following elements are not processed for NodeTypes:
- Requirements

The following elements are not processed for NodeTemplates:
- Interfaces
- Artifacts

Before starting to implement it we need to make clear if we really need to process these element.
If yes, for both we can take a look at the processing methods of the other one and hopefully (re-)use them.

**Comment by SamuelSorge** [comment]
It should be possible to process requirements in the node types (could be possible that there are nor requirements in the node templates, then we have to use the specified requriements in the node type.? Not really sure....).  Why are interfaces and artifacts not processed for Node Templates?

**Comment by seeebiii** [comment]
We have a specific class to parse NodeTemplates and there is no processing of interfaces or artifacts... I also assume that we need every point mentioned above, just wanted to think about it before we develop it blindly

**Comment by SamuelSorge** [comment]
Usually, if there are property definitions in node type definitions, these can be used to generate an xsd-file... One question: what about capability definitions in node types or node templates - which variant should be used:
1) # Simple definition is as follows: 
<capability_defn_name>: <capability_type> 

2)# The full definition is as follows: 
<capability_defn_name>: 
   type: <capability_type> 
   properties: 
     <property_definitions>

**Comment by seeebiii** [comment]
I'm not sure which definition we support, but I'll take a look at it in the evening ;)
If you have time, you can check the code by yourself, because this should already be implemented.

**Comment by seeebiii** [comment]
For NodeTypes and NodeTemplates we support the second notation, but without processing the properties :S There is a TODO in the corresponding NodeTemplate method

**Comment by iaavo** [comment]
Discussed in meeting: Interfaces and Artifacts are being ignored in NodeTemplate.
