### ISSUE TITLE
Add tests for each YAML test input file

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#102]
I've added new YAML test files in #100. If create at least one test file with good(!) tests, we will cover a lot functionality of the YAML transformer.

A test should be structured as this: read YAML file, test against the ServiceTemplate class if it contains the values you expect (don't test everything, but the most interesting properties/etc.) and then test if the XML output is as expected. For that you need to know how everything is mapped to XML. Take a look at the PDF in our dropbox (/yaml/CSAR_Template/Mapping-CaseStudy...).

Maybe you'll get errors while reading the YAML file. This might indicate a missing definition in the YAML test file or not supported definitions.
If you have any questions, write them down here.

**Comment by jonasheinisch** [comment]
Integrationstests
