### ISSUE TITLE
Make executable jar file 

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#109]
In order to present a successful result, we need to create a jar file which can be executed on the command line like `java -jar transformer.jar` and automatically calls our ConsoleUI class.

**Comment by seeebiii** [comment]
First how-to has been created by @jonasheinisch at https://github.com/CloudCycle2/YAML_Transformer/wiki/How-to-create-a-runnable-.jar-in-Eclipse

I will add a solution for Maven later.

**Comment by iaavo** [comment]
update wiki page: how to generate jar file.

**Comment by seeebiii** [comment]
maven clean package assembly:single

**Comment by iaavo** [comment]
https://github.com/CloudCycle2/YAML_Transformer/wiki/Build-from-source
Has now a detailed guide on generating the executable jar file

**Comment by iaavo** [comment]
Please merge #122 before attempting to build the jar file

**Comment by seeebiii** [comment]
The issue is implemented now.
