### ISSUE TITLE
DerivedFrom-Type in getCorrectTypeReferenceAsQName()

### ISSUE THREAD

**Issue by jonasheinisch** [CloudCycle2/YAML_Transformer#127]
The method getCorrectTypeReferenceAsQName() in TypeMapperUtil is sometimes used while creation of Types. The "derived_from"-value is used and must not be null or empty, but derived_from is not neccessary to define.

**Comment by seeebiii** [comment]
I just updated the lines where we are already creating such derived from objects. I can add an if condition to solve the problem.

**Comment by jonasheinisch** [comment]
Is this done?
