### ISSUE TITLE
Using timestamp in inputs in a yaml file is untested

### ISSUE THREAD

**Issue by iaavo** [CloudCycle2/YAML_Transformer#129]
Also a default date format needs to be defined. See org.opentosca.yamlconverter.main.utils.ConstraintUtils

**Comment by iaavo** [comment]
The date format is not converted correctly in all instances. It is also not ISO 8601 compliant. 
See also 
http://yaml.org/type/timestamp.html 
and 
http://stackoverflow.com/questions/12201233/convert-iso8601-string-date-time-format-to-date-in-java?rq=1
http://stackoverflow.com/questions/2201925/converting-iso-8601-compliant-string-to-java-util-date

**Comment by seeebiii** [comment]
And what do we need to do now to close this issue?!

**Comment by Deflaktor** [comment]
Im gonna work on it.

**Comment by iaavo** [comment]
Im gonna work on it
