### ISSUE TITLE
OpenTosca Container can't load CSAR (moodle)

### ISSUE THREAD

**Issue by SamuelSorge** [CloudCycle2/YAML_Transformer#143]
We have to check our generated CSAR, because the OpenTosca container is not able to load our moodle example. We testet the helloworld.yaml (\\org.opentosca.yamlconverter.main\src\main\resources\yaml) which is fine. Thus we should try to process our moodle example step by step starting with only a few nodes (without requirements etc).
For testing please use the described way in the mail "[yaml] Ansatz für Container-Problem" (keep in mind that the IP has changed to xxx.xxx.xxx.241. 
If questions arise depending the test environment feel free to ask sebastian or jaasiel

**Comment by SamuelSorge** [comment]
See the file Error_Output_Moodle.txt in Dropbox: \\DevPro\yaml

**Comment by iaavo** [comment]
I have found the problem:
There are several imports missing (ToscaBaseTypes xml, ToscaBaseTypes xsd, ToscaSpecificTypes xsd) 
That was quite a journey! :airplane:

**Comment by SamuelSorge** [comment]
Still not working, I also uploaded the CSAR into the winery and exported it again (Tipp by Marc/kus), unfortunately the Tosca container neither loads our csar nor the one which was exported by the winery

**Comment by msteffl** [comment]
Moodle.csar works now in OpenTosca Container
