### ISSUE TITLE
Create multiple YAML test files

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#19]
Last Tuesday our advisors mentioned we should create about 5 test files. Test files should include node templates and nodes should have at least one relation to another node.

**Comment by jonasheinisch** [comment]
Moodle, example, template

**Comment by SamuelSorge** [comment]
Michael and me: CSARTemplate Example YAML file generation.
Further work: Moodle and the complex ecample including relationship template and requirements

**Comment by seeebiii** [comment]
@SamuelSorge @msteffl 
Where do we stay here? I know we have a CSAR_Template.yml and three yaml files for Moodle, but how much work is left?

**Comment by SamuelSorge** [comment]
CSAR_Template (InstallVMServ) is quite ready for use (only TOSCA_definition.yaml should be commented out in the imports section (standard types)). The Moodle example is under construction (next week hopefully finished)

**Comment by jonasheinisch** [comment]
Enough tests made.
