### ISSUE TITLE
Complete Tosca YAML Model

### ISSUE THREAD

**Issue by jonasheinisch** [CloudCycle2/YAML_Transformer#28]
Completion of the Model

The use of VisualParadigm seems to be needed to discuss...

**Comment by iaavo** [comment]
Been discussed. Continuing to use VisualParadigm

**Comment by iaavo** [comment]
A few attribute maps are not correct yet. Map<String, String> instead of Map<String, Object> (?) 
The use of VisualParadigm from this point on is discouraged as the underlying code has a lot of changes applied to it.

**Comment by jonasheinisch** [comment]
In the *Types there are missing the derivedFrom-fields!

**Comment by seeebiii** [comment]
The classes ArtifactType, CapabilityType, NodeType and RelationshipType have a derived_from attribute (has been added the last days).
In my opinion the model is nearly complete, maybe there are some classes which we don't need at the moment like TypedProperty, Import, Group or OperationDefinition. This may have different causes. This need to be reviewed.

**Comment by jonasheinisch** [comment]
Though XML does not support groups, we maybe should parse groups. Each group contains multiple NodeTemplates. These could then be parsed to XML without a group. I think doing this should be simple as we already have everything to parse NodeTemplates.

**Comment by seeebiii** [comment]
Added an issue to parse groups #99

**Comment by seeebiii** [comment]
Yesterday we decided to not parse groups because of our project schedule. The model classes are working so far, so we can close this issue here.
