### ISSUE TITLE
Write Mapper that converts Tocsa YAML beans to XML beans

### ISSUE THREAD

**Issue by jonasheinisch** [CloudCycle2/YAML_Transformer#29]
A Mapper should be written for that.

As Dozer seems to be more overhead than use, because CustomConverter have to be programmed in most cases anyway, the use of Dozer should be discussed. Alternative suggestion would be programming a switch over classes or a visitor pattern. This has to be discussed.

**Comment by jonasheinisch** [comment]
Is this the best way? Maybe a converter that directly creates XML-text is better. @iaavo said it should be possible with maps.

**Comment by iaavo** [comment]
I have pushed a complete example on how to do this as a pullrequest xmllaxtest

**Comment by jonasheinisch** [comment]
@krauswg can you try this for our case?

In the meantime i developed a version that directly builds a XML-String. This seems to work very good for all YAML-elements that are so far present in the model. Also I already implemented the get_property method and prepared the get_input method. The get_ref_property seems to be a bit more complicated - depending on the implementation of the model (if there will be real references or just "variable" references)..

**Comment by jonasheinisch** [comment]
please merge #47 and #49

**Comment by seeebiii** [comment]
Merge is done by this morning, I think we can go on from here. From the milestone email:

This work should be done from 27.01. to 10.02.
Assignees: Jonas, Wolfgang

Can you confirm this?

**Comment by jonasheinisch** [comment]
:+1:

**Comment by seeebiii** [comment]
This can be closed, because it's to generic and the initial issue description is already implemented.
