### ISSUE TITLE
Recherche on Mapping

### ISSUE THREAD

**Issue by jonasheinisch** [CloudCycle2/YAML_Transformer#35]

**Comment by seeebiii** [comment]
For tomorrow: Is everything clear now? Respectively is the document ready to ask our advisors?

**Comment by SamuelSorge** [comment]
Working on this right now. Will be finished tomorrow afternoon

**Comment by seeebiii** [comment]
I think we can close this issue or do you have any concerns? @SamuelSorge @msteffl

**Comment by seeebiii** [comment]
Talked to @SamuelSorge, can be closed.
