### ISSUE TITLE
How to handle YAML-imports?

### ISSUE THREAD

**Issue by jonasheinisch** [CloudCycle2/YAML_Transformer#39]
We have several things we should discuss:
A) If there are imports in a yaml-file, how might we access the file? If we are doing this as a converter installed locally, this is simple: We should be able to access the referenced files directly. Problematic will be if we develop a library as a service. How can we assure that the user will submit all yaml-files? Or is the user supposed to submit a zip/csar-file?
B) What to do in case of imports?
Possible Solutions:
- 1) Use XML-imports
- 2) Parse all YAML-documents to one XML-file

**Comment by jonasheinisch** [comment]
Personal Comment to B:
1) Would be the much prettier solution, but it might become very difficult to handle the imports. In YAML references to other files can simply been done by name, but for XML we have to use a proper namespace, don't we? Then we have to check where the referenced element is defined and have to get its namespace and so on... Sounds very messy...
2) Not so pretty, but very easy in comparison.

**Comment by seeebiii** [comment]
for B): as we've discussed last Tuesday, the advisors would accept a single xml file which is fine for us and them.

for A): sounds a little bit tricky and I can't remember that we've talked about this problem before... one solution could be that we only accept absolut file paths. Then the user has to get keep an eye on this issue

**Comment by jonasheinisch** [comment]
@seeebiii for A) This assumes that we operate locally on the users machine. If the lib is used as a remote service, this would not solve the problem, as we can't access the file. For the local case if we pass the file, we could also work with relative pathes as we know at least the one folder...

**Comment by seeebiii** [comment]
thats correct, I was assuming a user really owns the file ;)

**Comment by seeebiii** [comment]
As discussed yesterday, we won't handle yaml imports in the converter (we assume that there is only one YAML file for the sake of simplicity), because it makes things very difficult if our program is used as a lib in CSAR Repository. This has to be considered for #19. If we have enough time later, we can think of a possible solution. So far, the issue can be closed.
