### ISSUE TITLE
No name for node templates

### ISSUE THREAD

**Issue by jonasheinisch** [CloudCycle2/YAML_Transformer#42]
NodeTemplates has been a map before with name as key. Now there is no name as it is only a list...

**Comment by iaavo** [comment]
Fixed with 7da373cfca0c6a3a9e490f71d193d9fe8b4a658b

**Comment by jonasheinisch** [comment]
Looks good! I will have a deeper look on the changes and TODOs, I recently wrote.

**Comment by jonasheinisch** [comment]
finished :+1:
