### ISSUE TITLE
Add property support in Tosca XML classes

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#51]
We had the problem that we could not integrate abitrary objects into any hierarchy of TDefinitions. We found a simple example with a class called "AnyMap" where we can store any property map. Is the task completed or do we still need to implement something?

**Comment by jonasheinisch** [comment]
There is still a problem with this. At the moment for a NodeTemplate with the type "XYType" the output is:
...
<Properties>
  <x>bla</x>
  <y>blubb</y>
</Properties>
...

But it should be:
...
<XYTypeProperties>
  <x>bla</x>
  <y>blubb</y>
</XYTypeProperties>
...

**Comment by krauswg** [comment]
Any specific reason why the properties should have the type name in it? The position of the element should be sufficient to identify where it belongs to.

**Comment by jonasheinisch** [comment]
On the one hand this is right, but on the other hand the Property-Element should defined by the NodeType.
If a simple rename is not possible, we should check if it works this way, too. Else we should just rename it, to cover conventions ;)

**Comment by jonasheinisch** [comment]
#86

**Comment by seeebiii** [comment]
Your commit has fixed our problems.
