### ISSUE TITLE
Read yaml file with inputs correctly

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#52]
This is the task to read a yaml file which includes some inputs. These inputs must be declared separately and should be filled by the user, e.g. make a second call. Otherwise the inputs will have a default value which is configured in our program, e.g. "##USER_INPUT##" (without quotes).

Working time: From 27.01. to 03.02.15
Assignees: Albert, Sebastian

**Comment by jonasheinisch** [comment]
We new defined that we will parse the getters in the bean2bean-phase. implemented it in #69

**Comment by seeebiii** [comment]
According to #69: you added a TODO in Yaml2XmlSwitch in line 365 regarding defaults.. take a look at Input class from models, there is a default defined, you might need to change it if you need to.

**Comment by jonasheinisch** [comment]
As I commented in #70 this does not solve the problem, but makes it even more difficult ;)

**Comment by seeebiii** [comment]
This issue is still open and not implemented, is it correct? In AbstractSubSwitch the method parseGetter has still a "TODO Type defaults"

**Comment by seeebiii** [comment]
Okay after thinking about it: I don't think we need a special output for each type, because either we define a default string which makes a user aware that he needs to set a property/input or we define nothing and a property would be empty which would lead to errors as well... So I close this issue now.
