### ISSUE TITLE
Integration of YAML-read and YAML-XML mapping

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#54]
We need to integrate the two sub-components YAML-read and YAML-XML mapping so that we have a kind of a chain which does both in a row and we're able to create a complete XML file.

Time: From 10.02. to 24.02.
Assignees: at least Wolfgang, Jonas, Albert, Sebastian

**Comment by jonasheinisch** [comment]
Is done by https://github.com/CloudCycle2/YAML_Transformer/blob/master/org.opentosca.yamlconverter.main/src/main/java/org/opentosca/yamlconverter/main/Parser.java

Still to do: implement getter

**Comment by seeebiii** [comment]
Already implemented
