### ISSUE TITLE
Console interface

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#55]
A console interface is needed to use our transformer as a standalone program.
It should take an argument of a YAML file and returns complete XML. User should be able to provide inputs which are required in the YAML document or he should be able to tell the program to use default values for the inputs.

Time: 24.02. to 03.03.
Assignees: Not known yet

**Comment by SamuelSorge** [comment]
What do we need as input? One YAML file or several zipped YAML files?

**Comment by jonasheinisch** [comment]
@SamuelSorge This question also refers to #39

**Comment by SamuelSorge** [comment]
As we discussed some of the questions with our "nannies":
We can provide one single YAML-file, but sometimes there are basic types like the rootNodeType. These type-definitions will be given by the imports-section and we should ignore these files and use the corresponding standard XML-type definitions. If there are specific type definitions as import, we should read in all files and decide wether we generate separate files for the node types/templates or put it all in one file.

**Comment by jonasheinisch** [comment]
So in some cases we have to import additional files right? I would suggest two alternatives how to handle this:
1) If we want to have everything inside one XML later, we should just take all yaml-files and parse them to YAMLbeans seperately. Then we implement a merger that is able to merge several YAML ServiceTemplates (should be simply merging all reference maps of the ServiceTemplate and removing all the imports).
2) If we want to have the same structure of imports, we should just call the converter for every import recursively, store a mapping of filenames (yamlfilename -> xmlfilename), apply this filename-mapping in the imports inside the switchmapper. Also we could only ask the user for an output-folder and preserve names (except endings switch from .yaml to .xml).

**Comment by jonasheinisch** [comment]
Spontaniously my favorite is the first one as this sounds simpler and the following tools in the toolchain do not consider readability anyway...

**Comment by seeebiii** [comment]
As discussed with the advisors and mentioned in #39 we rely on one YAML file and don't accept another one. All definitions need to be done within that file.

Referring to the issue topic "Console interface" this issue can be closed, because the interface has already been implemented in #61
