### ISSUE TITLE
Support for Constraint Clauses

### ISSUE THREAD

**Issue by iaavo** [CloudCycle2/YAML_Transformer#71]
Adding support for constraint clauses. E.g.
inputs:
  num_cpus:
    type: integer
    constraints:
      - in_range: { 2, 4 }

See also TOSCA Spec -> A.3.2 Constraint clause

**Comment by seeebiii** [comment]
@iaavo Found a bug: if you use in_range: {2, 4} and type in 2=4, it will accept the value.
The rest is okay and the issue can be closed after fixing it.

**Comment by seeebiii** [comment]
Okay forget it, my fault: I used in_range for an input of type "string"... Will close this issue then!
