### ISSUE TITLE
Write document what's missing in transformer

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#78]
We need a document to write down what's missing in the transformer.
Documentate:
- inconsistencies in Spec
- simplifications in our transformer
- what need to be changed in XML-output to have a valid XML which can be read by container

**Comment by seeebiii** [comment]
Requirements are not supported yet, because in the new YAML Spec there are no requirement types and in the old one there are only requirements with illegal YAML code

**Comment by seeebiii** [comment]
CapabilityTypes are supported like this:
node_template:
..capabilities:
....capability_name:
......type: capabilityTypeName

capability_types:
..capabilityTypeName:
....derived_from: XY
....[etc.]

**Comment by seeebiii** [comment]
If interfaces are used, we can't support the implementation name (or any other property) given in YAML, because the Tosca classes don't support this.
Example:
node_type:
..interfaces:
....InterfaceA:
......operationX:
........implementation: something

Here, the implementation "something" is lost at the moment.

**Comment by seeebiii** [comment]
Relationship types are supported now, but only with the interface constraint mentioned above.
Example:
relationship_types:
..typeA:
....derived_from: typeRoot
....description: DESCRIPTION
....interfaces:
......[...]
....valid_targets: [CapabilityXY]

**Comment by seeebiii** [comment]
According to #82 the "new" structure of a YAML file is not supported, we still rely on the one from the old spec.

**Comment by seeebiii** [comment]
According to NodeTypeImplementations: Only ImplementationArtifacts are supported in YAML -> all artifacts in NodeTypes are converted to ArtifactTemplates which are used by a corresponding ImplementationArtifact of a NodeTypeImplementation

**Comment by SamuelSorge** [comment]
YAML does not provide requirement types. There is a direct association with capabilities. There are three ways to use requirements:
1) - <requirement_name>: <entity_name>
2) - <requirement_name>: <capability_type_name>
3) - <requirement_name>: <node_name>
       relationship_type: <relationship_name>

We do not provide version 1. Version 2 is similar to XML requirement type. Version 3 is used to express relationship templates. For more details see the the mapping file (dropbox). I will do this in the next hours/minutes/seconds don't know ;)

**Comment by seeebiii** [comment]
In the CSAR Template we have a property where you can add credentials (in the original XML they are written as JSON string). If you want to use something like a JSON string, you need to put the whole string into double quotes, e.g. "{key:value}". If you need to set a string within that string, you have to use single quotes, e.g. you need to write "{key:'my-string'}"

**Comment by SamuelSorge** [comment]
We will fix this

**Comment by seeebiii** [comment]
I didn't address you specifically, my comment was just meant in general regarding to the issues' topic ^^ Just in case you thought I mean you

**Comment by iaavo** [comment]
NodeTemplates in YAML can have interfaces and artifacts. These properties are ignored as discussed in meeting.

**Comment by SamuelSorge** [comment]
Interfaces and artifacts are not supported when defined at node templates... 
No support of deployment  (maybe in further yaml specifications)
If there is ":" or similar strings in a description put the whole description within quotes.
file extensions in artifact types should be set within brackets (e.g.: "[war]")

**Comment by jonasheinisch** [comment]
Is this done?
