### ISSUE TITLE
Support capabilities for xml topology

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#83]
We still need to support capabilities like "server is deployed with a tool xy", etc.

**Comment by seeebiii** [comment]
Capabilities are supported in #84, but the properties defined in YAML file can't be converted to TOSCA models because there is no support for them. Need to discuss this

**Comment by seeebiii** [comment]
@jonasheinisch Yesterday we had to leave out the capabilities while importing the CSAR to Winery. Did the fix namespace fix in #93 solve the issue? If yes, I think we can close this issue.

**Comment by jonasheinisch** [comment]
I did not get any errors when importing the resulting XML files to the Winery so far. So I think this should be fixed.

**Comment by seeebiii** [comment]
Okay, so I will close it now.
