### ISSUE TITLE
Refactor Xml2YamlSwitch

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#88]
The class Xml2YamlSwitch has grown and contains many methods. We should consider a refactoring of the class, e.g. create services who handle node types, etc seperately. But before doing so, we have to discuss what kind of synchronization between these services would be needed, if any.

**Comment by jonasheinisch** [comment]
For this Phase I would only consider refactoring for code-quality and not for performance. So we should not make it parallel at the moment for dev/test-time reasons.

**Comment by jonasheinisch** [comment]
#89

**Comment by seeebiii** [comment]
:100: I support "refactoring for code-quality" ;) I think the refactoring in #89 is enough so far ;)
