### ISSUE TITLE
Generated CSAR is not accepted by Dev. Winery

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#95]
CSAR Archive is not accepted by Winery. Error: "TOSCA.meta does not exist" whereas a TOSCA.meta is provided under TOSCA-Metadata.
The archive was generated by importing CSAR_Template.yml and is provided in our dropbox under /DevPro/yaml/CSAR_Template/Failing_CSAR_Template.csar

If someone can reproduce the error or better fix it, I will appreciate that :) @jonasheinisch ?

**Comment by jonasheinisch** [comment]
regarding to tthe sources (https://eclipse.googlesource.com/winery/org.eclipse.winery/+/b40430f7c0847ecffb009b5113bde6d66c9a87af/org.eclipse.winery.repository/src/main/java/org/eclipse/winery/repository/importing/CSARImporter.java) that means, that there is simply no file "TOSCA-Metadata/TOSCA.meta". This is strange behaviour as I can't find any difference between the filenames... Can maybe someone test it on a linux-machine or similar? Maybe its some path problem or something like that...

**Comment by seeebiii** [comment]
I've talked to the Repo guys and they figured out that the packaging of the csar is not correct. I can't really explain it, but it has something to do with a subfolder packaging. You can't see it if you open the csar with WinRar etc. but we must make sure that the folders Definitions and TOSCA-Metadata are packaged from the same folder. We can discuss it later in our regular meeting ;)

**Comment by seeebiii** [comment]
This problem is solved now. The problem was that blackslashes have been used for each file name. Changed it to use regular slashes.
