### ISSUE TITLE
Write a document / Wiki page on how to use the transformer

### ISSUE THREAD

**Issue by seeebiii** [CloudCycle2/YAML_Transformer#98]
We need a document or a Wiki page where others can see how the transformer can be used.
This can be established by updating the README document in the root directory of this repository, by adding Wiki pages to this repository or by writing a PDF document.
The tutorial/how-to should include a description of the Parser interface, how to call it (and in which order! Take a look at ConsoleUI) and what can be expected as the output. Later we can merge this document with #78.
@jonasheinisch @krauswg @iaavo @SamuelSorge @msteffl If anyone has nothing to do, I will appreciate some initial work for that. Discussions and questions to the document should be done here.

**Comment by seeebiii** [comment]
Include to document:
Requirement for YAML files is that they end with *.yml and not *.yaml; maybe @SamuelSorge can write again why this was/is important (sorry, I forgot it :( )

**Comment by SamuelSorge** [comment]
I think the file ending doesn't matter as long as the content is correct.

**Comment by seeebiii** [comment]
:+1:

**Comment by krauswg** [comment]
I think it was the requirement for an external editor, which mapped only yml as yaml file. As far as I know the suffix doesn't matter for our parser.

**Comment by seeebiii** [comment]
Initial wiki pages created: https://github.com/CloudCycle2/YAML_Transformer/wiki

**Comment by iaavo** [comment]
https://github.com/CloudCycle2/YAML_Transformer/wiki
has a section about supported elements of specification.
it should probably be moved to https://github.com/CloudCycle2/YAML_Transformer/wiki/Limitations-and-capabilities
